### ISSUE TITLE
[Bug] Context "schema" not found, do you forget to inject it?

### ISSUE THREAD

**Issue by adaboese** [Milkdown/milkdown#1218]
### Initial checklist

- [X] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.3.3

### Steps to reproduce

It happens as soon as I try to call `ctx.get(schemaCtx)`.

I don't understand why given that schemaCtx should be always available (?)

```diff
.config((ctx) => {
  const selectionListener = ctx.get(selectionCtx.key);

  selectionListener.onSelection((selection) => {
+    const schema = ctx.get(schemaCtx);

    const view = ctx.get(editorViewCtx).state.doc;

    setSelection(normalizeSelection({ doc: view, schema, selection }));
  });
})
```

Is this somehow related to the implementation of `selectionListenerPlugin`?

```ts
import { InitReady } from '@milkdown/core';
import { type Node, type Schema } from '@milkdown/prose/model';
import {
  Plugin,
  PluginKey,
  type Selection,
  type Transaction,
} from '@milkdown/prose/state';
import { $ctx, $proseAsync } from '@milkdown/utils';
import { debounce } from '#app/utilities/debounce';

type Listener = (selection: Selection, doc: Node) => void;

class SelectionManager {
  private selectionListeners: Listener[] = [];

  public get listeners() {
    return {
      selection: this.selectionListeners,
    };
  }

  public onSelection(listener: Listener) {
    this.selectionListeners.push(listener);

    return this;
  }

  public selection: Selection | null = null;

  public setSelection(selection: Selection) {
    this.selection = selection;
  }
}

export const selectionCtx = $ctx(new SelectionManager(), 'selection-listener');

const key = new PluginKey('MILKDOWN_SELECTION_LISTENER');

const selectionListener = $proseAsync(async (context) => {
  await context.wait(InitReady);

  const listener = context.get(selectionCtx.key);

  const { listeners } = listener;

  let previousSelection: Selection | null = null;

  const debounceSelection = debounce((tr: Transaction) => {
    const { selection, doc } = tr;

    for (const listener of listeners.selection) {
      listener(selection, doc);
    }

    previousSelection = tr.selection;
  }, 200);

  return new Plugin({
    key,
    state: {
      apply: (tr: Transaction) => {
        if (previousSelection && tr.selection.eq(previousSelection)) {
          return;
        }

        listener.setSelection(tr.selection);

        debounceSelection(tr);
      },
      init: () => {
        // do nothing
      },
    },
  });
});

export const selectionListenerPlugin = [selectionCtx, selectionListener];

export type Mark =
  | 'strong'
  | 'emphasis'
  | 'strike_through'
  | 'ordered_list'
  | 'bullet_list'
  | 'blockquote';

export type Parent = 'paragraph' | 'heading-1' | 'heading-2' | 'heading-3';

export type NormalizedSection = {
  active: Mark[];
  headingLevel: number;
  parent: Parent | null;
};

export const normalizeSelection = ({
  doc,
  schema,
  selection,
}: {
  doc: Node;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  schema: Schema<any, any>;
  selection: Selection;
}): NormalizedSection => {
  const list: Mark[] = [];
  const { from, to } = selection;
  const resolvedPosition = doc.resolve(from);

  // @ts-expect-error TODO investigate why path is not in the type
  const { parent, path } = resolvedPosition;

  for (const maybeNode of path) {
    if (maybeNode.type) {
      list.push(maybeNode.type.name);
    }
  }

  for (const mark of Object.keys(schema.marks)) {
    if (
      doc.rangeHasMark(from === to ? from - 1 : from, to, schema.marks[mark])
    ) {
      list.push(schema.marks[mark].name as Mark);
    }
  }

  let parentNode: Parent | null = null;

  if (parent.type.name === 'paragraph') {
    parentNode = 'paragraph';
  } else if (parent.type.name === 'heading' && parent.attrs.level === 1) {
    parentNode = 'heading-1';
  } else if (parent.type.name === 'heading' && parent.attrs.level === 2) {
    parentNode = 'heading-2';
  } else if (parent.type.name === 'heading' && parent.attrs.level === 3) {
    parentNode = 'heading-3';
  }

  return {
    active: list,
    headingLevel: parent.attrs?.level || 0,
    parent: parentNode,
  };
};
```

### Expected behavior

I expect it to just work.

### Actual behavior

Getting error:

```
index.ts:14 Uncaught MilkdownError: Context "schema" not found, do you forget to inject it?
    at d (index.ts:14:10)
    at G.get (container.ts:22:13)
    at L2.use (ctx.ts:88:28)
    at L2.get (ctx.ts:92:80)
    at RichEditor.client.tsx:102:32
    at selectionListenerPlugin.ts:53:7
    at debounce.ts:9:30
```

### Runtime

Chrome

### OS

macOS

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
https://stackblitz.com/edit/github-sngfj8?file=src%2Fmain.ts
It seems cannot be reproduced. Maybe there're two versions of `@milkdown/core` in your code?

**Comment by adaboese** [comment]
It only happens when I add the editor to DOM, remove it, and then add again. It happens the second time it is added.

For context, I allow users to toggle between different editors.

This is the React component. Maybe I am missing some teardown logic?

```ts
/* eslint-disable import/no-unassigned-import */
/* eslint-disable unicorn/prevent-abbreviations */

import '@milkdown/prose/view/style/prosemirror.css';
import '@milkdown/prose/tables/style/tables.css';
import { highlightContext, highlightPlugin } from './HighlightPlugin';
import { linkPlugin } from './linkPlugin';
import {
  type NormalizedSection,
  normalizeSelection,
  selectionCtx,
  selectionListenerPlugin,
} from './selectionListenerPlugin';
import { Toolbar } from './Toolbar';
import {
  defaultValueCtx,
  Editor,
  editorViewCtx,
  editorViewOptionsCtx,
  rootCtx,
  schemaCtx,
} from '@milkdown/core';
import { type Ctx } from '@milkdown/ctx';
import { clipboard } from '@milkdown/plugin-clipboard';
import { cursor } from '@milkdown/plugin-cursor';
import { history } from '@milkdown/plugin-history';
import { listener, listenerCtx } from '@milkdown/plugin-listener';
import { commonmark } from '@milkdown/preset-commonmark';
import { gfm } from '@milkdown/preset-gfm';
import { Milkdown, MilkdownProvider, useEditor } from '@milkdown/react';
import {
  ProsemirrorAdapterProvider,
  useWidgetViewFactory,
} from '@prosemirror-adapter/react';
import { milkdownTheme } from '#app/routes/_public/Prose';
import { useState } from 'react';

type Keyword = {
  keyword: string;
};

const MilkdownEditor = ({
  contentMarkdown,
  keywords,
  onChange,
}: {
  readonly contentMarkdown: string;
  readonly keywords: readonly Keyword[];
  readonly onChange: (markdown: string) => void;
}) => {
  const [selection, setSelection] = useState<NormalizedSection>({
    active: [],
    headingLevel: 0,
    parent: null,
  });

  const widgetViewFactory = useWidgetViewFactory();

  const editor = useEditor(
    (root) => {
      return Editor.make()
        .config((ctx) => {
          ctx.set(rootCtx, root);
          ctx.set(defaultValueCtx, contentMarkdown);
        })
        .config((ctx: Ctx) => {
          console.log('first config');

          ctx.update(editorViewOptionsCtx, (previous) => ({
            ...previous,
            attributes: {
              class: 'milkdown-aimd-theme',
            },
          }));

          const listener = ctx.get(listenerCtx);

          listener.markdownUpdated((context_, markdown, previousMarkdown) => {
            console.log('markdownUpdated');

            if (markdown !== previousMarkdown) {
              onChange(markdown);

              const selectionListener = ctx.get(selectionCtx.key);

              if (selectionListener.selection) {
                const schema = ctx.get(schemaCtx);

                const view = ctx.get(editorViewCtx).state.doc;

                setSelection(
                  normalizeSelection({
                    doc: view,
                    schema,
                    selection: selectionListener.selection,
                  }),
                );
              }
            }
          });
        })
        .config((ctx) => {
          console.log('second config');

          const selectionListener = ctx.get(selectionCtx.key);

          selectionListener.onSelection((selection) => {
            console.log('onSelection');

            const schema = ctx.get(schemaCtx);

            console.log('after ctx.get(schemaCtx)');

            const view = ctx.get(editorViewCtx).state.doc;

            setSelection(normalizeSelection({ doc: view, schema, selection }));
          });
        })
        .use(listener)
        .use(gfm)
        .use(commonmark)
        .use(history)
        .use(clipboard)
        .use(cursor)
        .use(selectionListenerPlugin)
        .config((ctx) => {
          ctx.set(
            highlightContext.key,
            keywords.map((keyword) => keyword.keyword),
          );
        })
        .use(highlightPlugin)
        .use(linkPlugin(widgetViewFactory));
    },
    [onChange],
  );

  if (!editor) {
    return null;
  }

  return (
    <>
      <Toolbar
        editor={editor}
        selection={selection}
      />

      <div className={milkdownTheme}>
        <Milkdown />
      </div>
    </>
  );
};

export const RichEditor = ({
  contentMarkdown,
  keywords,
  onChange,
}: {
  readonly contentMarkdown: string;
  readonly keywords: readonly Keyword[];
  readonly onChange: (markdown: string) => void;
}) => {
  return (
    <MilkdownProvider>
      <ProsemirrorAdapterProvider>
        <MilkdownEditor
          contentMarkdown={contentMarkdown}
          keywords={keywords}
          onChange={onChange}
        />
      </ProsemirrorAdapterProvider>
    </MilkdownProvider>
  );
};
```
